### ISSUE TITLE
Exception when copying files after download

### ISSUE THREAD

**Issue by smathot** [dschreij/opensesame-extension-osf#17]
I received the following automated bug report. I'm not sure where it comes from.

~~~
Traceback (most recent call last):
  File "C:\Users\Public\Documents\opensesame_3.2.1-py2.7-win32-2\opensesame_3.2.1-py2.7-win32-2\lib\site-packages\QOpenScienceFramework\manager.py", line 401, in <lambda>
    callback, *args, **kwargs
  File "C:\Users\Public\Documents\opensesame_3.2.1-py2.7-win32-2\opensesame_3.2.1-py2.7-win32-2\lib\site-packages\QOpenScienceFramework\manager.py", line 860, in __reply_finished
    callback(reply, *args, **kwargs)
  File "C:\Users\Public\Documents\opensesame_3.2.1-py2.7-win32-2\opensesame_3.2.1-py2.7-win32-2\share\opensesame_extensions\OpenScienceFramework\OpenScienceFramework.py", line 1175, in __process_file_info
    self.compare_versions(data)
  File "C:\Users\Public\Documents\opensesame_3.2.1-py2.7-win32-2\opensesame_3.2.1-py2.7-win32-2\share\opensesame_extensions\OpenScienceFramework\OpenScienceFramework.py", line 569, in compare_versions
    shutil.copy(self.main_window.current_path, destination)
  File "C:\Users\Public\Documents\opensesame_3.2.1-py2.7-win32-2\opensesame_3.2.1-py2.7-win32-2\lib\shutil.py", line 119, in copy
    copyfile(src, dst)
  File "C:\Users\Public\Documents\opensesame_3.2.1-py2.7-win32-2\opensesame_3.2.1-py2.7-win32-2\lib\shutil.py", line 69, in copyfile
    raise Error("`%s` and `%s` are the same file" % (src, dst))
Error: `C:/[path hidden for privacy].osexp` and `C:/[path hidden for privacy].osexp` are the same file
~~~

**Comment by dschreij** [comment]
Hmm, this appears to be one of our own errors. It's a failsafe to prevent a user to copy a file to itself, and  it appears to work :) I'm not sure in what kind of context this is happening though, or the action that the user is peforming. I need to have a closer look into this.
